version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      container_name: ets2la-cdn
    ports:
      - "9982:8000"
    volumes:
      - /mnt/sdb3/ets2la-cdn/datasets:/datasets
      - /mnt/sdb3/ets2la-cdn/models:/models
    healthcheck:
      test: ["CMD", "curl", "-f", "https://cdn.ets2la.com/heartbeat"]
      interval: 5m
      timeout: 3s